global:
  smtp_smarthost: 'localhost:25'
  smtp_from: 'alert@example.org'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'password'

templates: 
- '/etc/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h 
  receiver: alert_email
  
  routes:
  - match_re:
      service: ^(foo1|foo2|baz)$
    receiver: alert_email
    routes:
    - match:
        severity: critical
      receiver: alert_email

receivers:
- name: 'alert_email'
  email_configs:
  - to: 'alert@example.com'